# Generated by Django 4.1.7 on 2023-10-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_county_health_worker_workerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='medication_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageID', models.IntegerField()),
                ('medicationName', models.CharField(max_length=255, null=True)),
                ('batchNumber', models.CharField(max_length=255, null=True)),
                ('expiryDate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Delivered', 'Delivered')], max_length=255, null=True)),
                ('Institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.institution')),
                ('county_Health_Worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.county_health_worker')),
            ],
        ),
    ]
