# Generated by Django 4.1.7 on 2023-10-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa')], max_length=255, null=True),
        ),
    ]
