# Generated by Django 4.1.7 on 2023-10-27 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0009_medicationdistribution_county_health_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationdistribution',
            name='county_Health_Worker',
        ),
        migrations.AddField(
            model_name='medicationdistribution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
