# Generated by Django 4.1.7 on 2023-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_medicationdistribution_county_health_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication_package',
            name='id',
        ),
        migrations.AlterField(
            model_name='medication_package',
            name='packageID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
