# Generated by Django 4.1.7 on 2023-11-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_institutionallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdistribution',
            name='allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.institutionallocation'),
        ),
    ]
