# Generated by Django 4.1.7 on 2023-11-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_medicationdistribution_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.medicationdistribution'),
        ),
    ]
